### ISSUE TITLE
The TSnackBar is showing over the ToolBar

### ISSUE THREAD

**Issue by geekyfox90** [AndreiD/TSnackBar#1]
I tried the TSnackBar library with all the requirements you mentioned, but the TSnackBar is showing over the ToolBar.

Is there any way I can do about it ?

**Comment by AndreiD** [comment]
wrote it in the description @ troubleshooting....

Notice that, if you use findViewById(android.R.id.content) your snackbar might appear over your notifications bar (the one with the clock, battery). To fix it, replace it with your view, coordinator layout etc.

**Comment by geekyfox90** [comment]
I've tried to place that with my CoordinatorLayout, or my ToolBar view, but I have the same issue

**Comment by AndreiD** [comment]
so instead of android.R.id.content put "R.id.relativelayout_activity_name" ... or the name of your layout

**Comment by AndreiD** [comment]
can you copy-paste your layout here ?

**Comment by geekyfox90** [comment]
```
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    tools:context=".MainActivity">

   <LinearLayout
       android:orientation="vertical"
       android:layout_width="fill_parent"
       android:layout_height="fill_parent">

       <android.support.v7.widget.Toolbar

           android:id="@+id/toolbar"
           android:layout_width="match_parent"
           android:layout_height="wrap_content"
           android:minHeight="?attr/actionBarSize"
           android:background="?attr/colorPrimary"
           android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

<ImageView
    android:layout_width="75dp"
    android:layout_height="28dp"
    android:src="@drawable/athena"/>



       </android.support.v7.widget.Toolbar>








       <ProgressBar
           android:layout_width="wrap_content"
           android:layout_height="wrap_content"
           android:id="@+id/progressBar5"
           android:layout_marginTop="10dp"
           android:layout_gravity="center_horizontal" />

       <android.support.v4.widget.SwipeRefreshLayout
           android:id="@+id/swipeRefreshLayout"
           android:layout_width="match_parent"
           android:layout_height="match_parent">

           <android.support.v7.widget.RecyclerView
               android:id="@+id/my_recycler_view"
               android:layout_width="match_parent"
               android:layout_height="wrap_content"
               android:scrollbars="vertical" />
       </android.support.v4.widget.SwipeRefreshLayout>







   </LinearLayout>






    <com.melnykov.fab.FloatingActionButton
        android:id="@+id/add"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|bottom"
        android:layout_margin="16dp"
        fab:fab_colorNormal="@color/colorPrimary"
        android:src="@drawable/ic_action_name9" />

    </android.support.design.widget.CoordinatorLayout>

```

**Comment by AndreiD** [comment]
true. seems that the problem lies in this "findSuitableParent". I'll take a look at it on the next release.

**Comment by geekyfox90** [comment]
There is no alternative solution ?

**Comment by AndreiD** [comment]
you can try with https://github.com/keyboardsurfer/Crouton if you don't require action buttons.

**Comment by geekyfox90** [comment]
I require action buttons, I will wait for the next release

**Comment by AndreiD** [comment]
fixed in version 0.0.8. make sure the view doesn't have padding.

**Comment by geekyfox90** [comment]
Thank you

**Comment by geekyfox90** [comment]
I've tried the new version, but I'm facing the same issue, could you help please ?

**Comment by AndreiD** [comment]
Can't be. I tried it on your code... 0.0.8 ?

**Comment by geekyfox90** [comment]
Yes 0.0.8 it showing over the Toolbar, I used it with my Coordinator Layout findViewById(R.id.CoordinatorLayout)

**Comment by AndreiD** [comment]
and don't you see that your coordinatorlayout INCLUDES the toolbar ? you have to use a layout that does not include it. Try with swipeRefreshLayout or if it's not working, try adding a layout after it

**Comment by GauravP123** [comment]
any way we can add position like top bottom

**Comment by Ergi16** [comment]
TSnackbar snackbar = TSnackbar
                .make(findViewById(android.R.id.content)"Some text", TSnackbar.LENGTH_LONG);
        View view = snackbar.getView();
        FrameLayout.LayoutParams params =(FrameLayout.LayoutParams)view.getLayoutParams();
        snackbar.setActionTextColor(Color.BLACK);
       // snackbar.setIconRight(R.drawable.dark_close, 15);
        snackbar.setIconPadding(8);
        snackbar.setAction("Close", new View.OnClickListener() {
           @Override
           public void onClick(View view) {
               snackbar.dismiss();
           }
       });

        View snackbarView = snackbar.getView();
        snackbarView.setBackgroundColor(Color.parseColor("#FFFFFF"));
        TextView textView = (TextView) snackbarView.findViewById(com.androidadvance.topsnackbar.R.id.snackbar_text);
        textView.setTextColor(Color.BLACK);
        TypedValue tv = new TypedValue();
        int actionBarHeight=0;
        if (getTheme().resolveAttribute(R.attr.actionBarSize, tv, true))
        {
            actionBarHeight = TypedValue.complexToDimensionPixelSize(tv.data,getResources().getDisplayMetrics());
        }

// set margin
        params.setMargins(0, actionBarHeight, 0, 0);

        view.setLayoutParams(params);
        snackbar.show();
        
        ///////
        It got margin same as toolbar size
