### ISSUE TITLE
Sometimes it does not show

### ISSUE THREAD

**Issue by ghost** [AndreiD/TSnackBar#14]
I do not know why, it does not show, I setted it behind the Toolbbar. I found that when i start an activity when it is still showing on the current activity, i won't show any more. For example, I show it in LoginActivity as a test, but when I start MainActivity when it is still showing, the TSnackbar won't showing anymore. It seems that you have to wait till the current showing TSnackbar is hidden. I am an Android beginner.

**Comment by AndreiD** [comment]
can you copy paste some code here ?

**Comment by BetaStrike** [comment]
I am also running into this issue.

in our case I had a first activity that launches a second activity with taskAffinity singleTop and in the intent we give it cleartop flag (IE we force the creation of a new activity and go thru onCreate). 

if in the second activity we show a snackbar, and it is not dismissed before going back to the first activity (with the back button), on the next launch of the second activity the TSnackbar will break.

I can provide code if needed, but it seems like that is an issue.

**Comment by AndreiD** [comment]
if you clone it and import it in your project still the same? so NOT from
the gradle file

**Comment by TheHolyLancer** [comment]
when i try to do that I get 

Error:Plugin with id 'com.jfrog.bintray' not found.

I attempted to add it via module import (only the inner most one, not the sample app)

and via settings.gradle and adding its path as a

**Comment by BetaStrike** [comment]
when i try to do that I get 

Error:Plugin with id 'com.jfrog.bintray' not found.

I attempted to add it via module import (only the inner most one, not the sample app)

and via settings.gradle and adding its path as a project. /cloned-dir/topsnackbar

I will now try just manually copying the files over...

**Comment by ghost** [comment]
I gave it up for this bug, so I can not provide any code, sorry.

**Comment by raaf003** [comment]
I have noticed something like that .....I have an activity which shows snackbar if there is no internet connection....now if the snackbar is not dismissed and I go away from the activity like pressing home key , when I come back the snackbar won't show untill I kill the app.

**Comment by sungjin0213** [comment]
This also happened to me, but using latest version (not Gradle one) seems like resolved this issue. Please update Gradle so that future users might not have this issue.

**Comment by AndreiD** [comment]
I'll update the readme now.

**Comment by SheepYang1993** [comment]
> I have noticed something like that .....I have an activity which shows snackbar if there is no internet connection....now if the snackbar is not dismissed and I go away from the activity like pressing home key , when I come back the snackbar won't show untill I kill the app.

I have the same problem
