### ISSUE TITLE
Show TSnaskBar under statusbar

### ISSUE THREAD

**Issue by Yavin86** [AndreiD/TSnackBar#16]
It is possible to show TSnaskBar under statusbar?
now:
![ecc2bf4dca](https://cloud.githubusercontent.com/assets/2663992/15078717/521e9faa-13d6-11e6-8672-cae989ae8a18.jpg)
![2df68fa6fe](https://cloud.githubusercontent.com/assets/2663992/15078984/b8694692-13d7-11e6-8e7b-7ad0a069834e.jpg)
target:
![ecc2bf4dca2](https://cloud.githubusercontent.com/assets/2663992/15078937/7e9713d6-13d7-11e6-8454-dd1b71e75f7d.jpg)

**Comment by MrLepage** [comment]
Please refer to this post to draw content behing status bar :
http://stackoverflow.com/questions/27856603/lollipop-draw-behind-statusbar-with-its-color-set-to-transparent

**Comment by Qamar4P** [comment]
@AndreiD can you fix this issue so that this work independent like we can give it offset
