### ISSUE TITLE
Manifest merger issue

### ISSUE THREAD

**Issue by tnache** [AndreiD/TSnackBar#2]
Hi, 
I am using your library in my project, but I am facing an issue with the Manifest merger, which complains about conflicting attributes in my main Manifest file and the manifest of your library. 

I would like to suggest to remove all attributes from the application tag in the manifest and leave it empty. That would be sufficient for resolving such issues when adding the library as gradle dependency in other projects.

Thanks,
Tsvetan

**Comment by AndreiD** [comment]
thanks for letting me know.

try with

```
compile 'com.androidadvance:topsnackbar:0.0.9'
```

**Comment by tnache** [comment]
Now it is fine. Thanks for your fast response :)
