### ISSUE TITLE
这个库会导致我的tablayout每次启动都全选中

### ISSUE THREAD

**Issue by taany6210** [AndreiD/TSnackBar#20]
![qq 20160725142726](https://cloud.githubusercontent.com/assets/13641640/17092286/1d086f3a-5274-11e6-9149-874dad46922d.jpg)
只要不引用这个库就没问题，引用了不用也是全选中。

**Comment by AndreiD** [comment]
if you don't write in english... i can't understand you..

**Comment by taany6210** [comment]
As long as the compile your library will lead to the following tabs all initialization time is selected.  Tabs is google TabLayout.Even if don't use your library.

**Comment by AndreiD** [comment]
so what are you saying ?

**Comment by taany6210** [comment]
All is your library cause TabLayout initialization time is selected.

**Comment by AndreiD** [comment]
sorry man, I give up... can't understand you.
