### ISSUE TITLE
android.view.InflateException: Binary XML file line #17: Error inflating class com.androidadvance.topsnackbar.TSnackbar$SnackbarLayout

### ISSUE THREAD

**Issue by azhen111** [AndreiD/TSnackBar#25]
android.view.InflateException: Binary XML file line #17: Error inflating class com.androidadvance.topsnackbar.TSnackbar$SnackbarLayout
whats wrong?help me,thank you

**Comment by AndreiD** [comment]
maybe you didn't add the library in gradle ?

**Comment by azhen111** [comment]
I find reason ,BaseActivity must extends AppCompatActivity
