### ISSUE TITLE
Cancel/remove Snackbar when user touch on any parts of screen

### ISSUE THREAD

**Issue by GauravP123** [AndreiD/TSnackBar#29]
When tooltip is visible and user click on any other part of the screen say user click on button and tooltip is visible and then user click on different button is any way we can cancel or remove Snackbar instead of waiting for Snackbar duration time to get overWhen Snackbar is visible and user click on any other part of the screen say user click on button and Snackbar is visible and then user click on different button is any way we can cancel or remove Snackbar instead of waiting for tooltip duration time to get over

**Comment by AndreiD** [comment]
why don't you call "dismiss" ?

**Comment by GauravP123** [comment]
remove the view like after duration its automatically removed

**Comment by Kolyall** [comment]
@AndreiD I called show()...then dismiss() and the show() again
it does't show at second time

**Comment by GauravP123** [comment]
@Kolyall but how you gets other layout click as u cant set on all views onclick do dismiss Snackbar

**Comment by Kolyall** [comment]
@AndreiD is it ok, that Snackbar does't show after dismiss?

**Comment by GauravP123** [comment]
@Kolyall my qus is if Snackbar is present and user click on any other part/view of the screen,it should dismiss

**Comment by Kolyall** [comment]
@GauravP123 you can do it by calling this method for your rootView:
 public void setupUI(View view) {

```
    if (!(view instanceof EditText)) {
        view.setOnTouchListener(new View.OnTouchListener() {
            public boolean onTouch(View v, MotionEvent event) {
                hideSnackBar();
                return false;
            }
        });
    }

    if (view instanceof ViewGroup) {
        for (int i = 0; i < ((ViewGroup) view).getChildCount(); i++) {
            View innerView = ((ViewGroup) view).getChildAt(i);
            setupUI(innerView);
        }
    }
}
```

**Comment by Shyri** [comment]
I'm having same problem as @Kolyall. After calling dismiss I cannot show again, but with Android's Snackbar that is possible.

**Comment by Kolyall** [comment]
@GauravP123 you can do it by calling this method for your rootView:
 public void setupUI(View view) {
      
        if (!(view instanceof EditText)) {
            view.setOnTouchListener(new View.OnTouchListener() {
                public boolean onTouch(View v, MotionEvent event) {
                    hideSnackBar();
                    return false;
                }
            });
        }

        if (view instanceof ViewGroup) {
            for (int i = 0; i < ((ViewGroup) view).getChildCount(); i++) {
                View innerView = ((ViewGroup) view).getChildAt(i);
                setupUI(innerView);
            }
        }
    }

**Comment by Kolyall** [comment]
@Shyri seems that dev ignore issues..and the repo is not supported any more

**Comment by AndreiD** [comment]
Yes, no time to look into it. But I have an idea...., why don't you make a PR for this issue and I'll find some time to update it.
