### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [AndreiD/TSnackBar#3]

**Comment by AndreiD** [comment]
Thanks for reminding it. I've added

**Comment by vbauer** [comment]
Thank you for information.

**Comment by AndreiD** [comment]
you have me a message to put the badge from your website but I can't find it. can you give it to me again please

**Comment by vbauer** [comment]
On each page (ex: http://android-arsenal.com/details/1/2779) there is a link ("Generate") to generate badge for the current project. It would be great if you can add them. :)
