### ISSUE TITLE
Landscape Softkey moves view up, snackbar start is moved up

### ISSUE THREAD

**Issue by ersin-ertan** [AndreiD/TSnackBar#35]
In landscape mode, when the softkey opens, and I call a snackbar, I pass in my 
`activity.getWindow().getDecorView().getRootView()` and  the view is moved up thus the snack bar starts at the top of the view bottom, and only 10% of the snackbar view is visible at the end of the animation.

**Comment by AndreiD** [comment]
so what are you proposing ?

**Comment by ersin-ertan** [comment]
Solved via: 
```java
    TSnackbar tSnackbar = TSnackbar.make(view.getRootView(), stringRes, TSnackbar.LENGTH_SHORT)
        .setMaxWidth(view.getRootView().getWidth());
    View v = tSnackbar.getView();
    v.setFitsSystemWindows(true);
```
