### ISSUE TITLE
Include custom icon on "dismiss" button

### ISSUE THREAD

**Issue by yannbf** [AndreiD/TSnackBar#37]
So I was wondering if it's possible to implement a way  to add a custom icon at the same place that "UNDO" is supposed to be. I was able to add an icon on the left and it was great, but I need to also add a "close" custom icon on the right side.

Thank you for this great lib, and I would appreciate if you could help me out on that.

**Comment by AndreiD** [comment]
so how to help you ? like stop what I'm doing now, write the code for you, and give you a message "Hi Yannbf, can you please tell me if I wrote it good enough for your liking ?"

**Comment by yannbf** [comment]
I am sorry if it sounded like a request, I was actually asking for help to think on how to do that. As you are the creator of this plugin, perhaps you could give a few ideas that could have helped me out modify the existing source code. I ended up making it work, anyways.

I don't know if you had a bad day or something, but this was unnecessarily rude. 

Thanks for your time.

**Comment by Palantir-NR** [comment]
TSnackbar snackbar = TSnackbar.make(findViewById(android.R.id.content), value, TSnackbar.LENGTH_LONG);
        snackbar.setActionTextColor(Color.WHITE);
        View snackbarView = snackbar.getView();
        snackbarView.setBackgroundColor(ContextCompat.getColor(this, R.color.error));
        TextView textView = snackbarView.findViewById(com.androidadvance.topsnackbar.R.id.snackbar_text);
        textView.setTypeface(textView.getTypeface(), Typeface.BOLD);
        snackbar.setAction(" ", v -> snackbar.dismiss());
        TSnackbar.SnackbarLayout snackbarLayout = (TSnackbar.SnackbarLayout) snackbar.getView();
        for (int i = 0; i < snackbarLayout.getChildCount(); i++) {
            View view = snackbarLayout.getChildAt(i);
            if (view instanceof Button) {
                Button button = (Button) view;
                button.setBackground(ContextCompat.getDrawable(this, R.drawable.ic_close));
                LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) button.getLayoutParams();
                params.height = 64;
                params.width = 64;
                button.setLayoutParams(params);
            }
        }

        snackbar.show();

**Comment by Palantir-NR** [comment]
`public void showErrorSnackBar(String value) {
        TSnackbar snackbar = TSnackbar.make(findViewById(android.R.id.content), value, TSnackbar.LENGTH_LONG);
        snackbar.setActionTextColor(Color.WHITE);
        View snackbarView = snackbar.getView();
        snackbarView.setBackgroundColor(ContextCompat.getColor(this, R.color.error));
        TextView textView = snackbarView.findViewById(com.androidadvance.topsnackbar.R.id.snackbar_text);
        textView.setTypeface(textView.getTypeface(), Typeface.BOLD);
        snackbar.setAction(" ", v -> snackbar.dismiss());
        TSnackbar.SnackbarLayout snackbarLayout = (TSnackbar.SnackbarLayout) snackbar.getView();
        for (int i = 0; i < snackbarLayout.getChildCount(); i++) {
            View view = snackbarLayout.getChildAt(i);
            if (view instanceof Button) {
                Button button = (Button) view;
                button.setBackground(ContextCompat.getDrawable(this, R.drawable.ic_close));
                LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) button.getLayoutParams();
                params.height = 64;
                params.width = 64;
                button.setLayoutParams(params);
            }
        }

        snackbar.show();
    }`

**Comment by Palantir-NR** [comment]
`

public void showErrorSnackBar(String value) {
        TSnackbar snackbar = TSnackbar.make(findViewById(android.R.id.content), value, TSnackbar.LENGTH_LONG);
        snackbar.setActionTextColor(Color.WHITE);
        View snackbarView = snackbar.getView();
        snackbarView.setBackgroundColor(ContextCompat.getColor(this, R.color.error));
        TextView textView = snackbarView.findViewById(com.androidadvance.topsnackbar.R.id.snackbar_text);
        textView.setTypeface(textView.getTypeface(), Typeface.BOLD);
        snackbar.setAction(" ", v -> snackbar.dismiss());
        TSnackbar.SnackbarLayout snackbarLayout = (TSnackbar.SnackbarLayout) snackbar.getView();
        for (int i = 0; i < snackbarLayout.getChildCount(); i++) {
            View view = snackbarLayout.getChildAt(i);
            if (view instanceof Button) {
                Button button = (Button) view;
                button.setBackground(ContextCompat.getDrawable(this, R.drawable.ic_close));
                LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) button.getLayoutParams();
                params.height = 64;
                params.width = 64;
                button.setLayoutParams(params);
            }
        }

        snackbar.show();
    }

`

**Comment by Palantir-NR** [comment]
https://gist.github.com/Palantir-NR/db01e56d2be2b59c280b5162abae39b8
