### ISSUE TITLE
Sometimes,the snackbar cannot be timeout based on Snackbar.LENGTH_LONG

### ISSUE THREAD

**Issue by OVERSKY2003** [AndreiD/TSnackBar#4]
Sometimes,the snackbar cannot be timeout based on Snackbar.LENGTH_LONG and it is aways here.

**Comment by AndreiD** [comment]
y... I noticed this too. Will look into it as soon as I have some time.

**Comment by AurelienLepage** [comment]
I encountered the same bug, sometimes, the snackbar does not disappear.

**Comment by AndreiD** [comment]
this -> http://stackoverflow.com/questions/30926380/how-can-i-be-notified-when-a-snackbar-has-dismissed-itself

**Comment by OVERSKY2003** [comment]
how is the solution?

**Comment by AndreiD** [comment]
please update to the latest version
