### ISSUE TITLE
Disable Swipe right to close snackbar?

### ISSUE THREAD

**Issue by tuhin10** [AndreiD/TSnackBar#6]

**Comment by AndreiD** [comment]
i don't understand what you want....

**Comment by tuhin10** [comment]
i mean when we show the Snackbar as TSnackbar.LENGTH_INDEFINITE it should not alowed to be canceled by the user. But in this case if you swipe right on the snackbar, it gets dismissed. Can we disable this ??

**Comment by AndreiD** [comment]
I don't know. Maybe in your case a direct hidden layout should be more appropriate since snackbar acts like a "notification" more...

**Comment by tuhin10** [comment]
ok, will try to find an workaround for this. Thanx for the nice lib.
