### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by AndreiD** [AndreiD/TSnackBar#68]
Sadly I don't have time to maintain this project anymore.
if any of you feels like doing it, please drop me a message in this issue.

thank you!

**Comment by zoe00** [comment]
Hi,  I can be the maintainer for this :))

**Comment by AndreiD** [comment]
sure

**Comment by Arnaudv6** [comment]
I am at a loss: no more "maintainer wanted" in README,

- README points to another repo `implementation 'com.github.Redman1037:TSnackBar:V2.0.0'`
- but the only 2 commits on that fork/repo where modifs to README, in April, merged here before another commit from June.

@AndreiD, do you still have control on your project?
If This is dead, please state this clearly in README

**Comment by AndreiD** [comment]
it's dead man, fuck android.... get out of this stupid pice of crap world of mobile dev

**Comment by Arnaudv6** [comment]
Thanks.
