### ISSUE TITLE
大神您好！复杂布局不能正确弹出 看不到效果

### ISSUE THREAD

**Issue by maobon** [AndreiD/TSnackBar#7]
发现个小问题 主布局是CoordinatorLayout 内层是一个AppBarLayout 和一个可滚动的控件，AppBarLayout内部是一个collapsingToolbarLayout，目前不能看到顶部弹出Snackbar的效果，看不到效果，不知道是不是第一个参数给的有问题 我给的是最外层的协调器布局。

**Comment by AndreiD** [comment]
can't understand what are you saying with google translate. can you write in English ?
