### ISSUE TITLE
What tools do you use to convert mp4 file to gif file so small? Look forward your share. 

### ISSUE THREAD

**Issue by matrixxun** [AndreiD/TSnackBar#9]
Hi AndreiD, 

I have noticed that your demonstration gif file is very small(just 778k). I know you use the app named "AZ Screen Record" to record screen on android platform. but which tools do you use to convert mp4 file to gif file so small? Look forward your share. 

Best Regards
Matrixxun.

**Comment by AndreiD** [comment]
hello... I think I searched for a free online tool to convert mp4 to gifs. I know there a bunch of them, you'll have to test 3-4 until you find a good one. I forgot the name...but it's online and it's free
